### ISSUE TITLE
Add webstorm configure file in gitignore

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [travlog/travlog-server#15]
웹스톰을 쓰는 관계로 설정 파일 ignore 처리 하겠습니다.

**Comment by rkdgusrnrlrl** [comment]
@devjin0617 푸시 할 때 어떻게 하나요 ㅠㅠ 아래 같이 뜹니다.
```
Failed with error: unable to access
```

**Comment by fobid** [comment]
앗! 초대 된 사람 아니면 접근을 못하나봐요

**Comment by devjin0617** [comment]
와우 어서오세요!

@fobid github 조직에 초대 되나요?

**Comment by devjin0617** [comment]
@fobid 프로젝트 내에 메인테이너를 추가하거나 트라부ㅡ로그에 멤버로 추가해야 권한이 생길거예요 😄

**Comment by fobid** [comment]
물론이죠 환영합니다.
제가 멤버가 아니면 repository read 권한만 설정해놨었습니다..

**Comment by fobid** [comment]
**트라부ㅡ로그**에 멤버로 초대해드렸습니다.

환영 선물입니다.
https://www.youtube.com/watch?v=CjbXBqK8_VA

**Comment by rkdgusrnrlrl** [comment]
@fobid ㅋㅋㅋ 격한 환영 감사합니다. 곧 PR 로 찾아 뵙겠습니다. ㅋㅋㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
@fobid 우선 팀에 조인 했습니다만.... 푸시가 여전이 안되네요 브랜치를 devlop 에서 따서 그런가요 ㅠㅠ

**Comment by devjin0617** [comment]
클론자체를 해당 저장소를 받으셔야 할꺼예요 : )
