### ISSUE TITLE
비밀번호 암호화

### ISSUE THREAD

**Issue by fobid** [travlog/travlog-server#27]
http://www.hani.co.kr/arti/international/america/843311.html

**Comment by rkdgusrnrlrl** [comment]
비밀번호는 보통 bcrypt 를 많이 사용 하는 걸로 알고 있습니다. 제가 있는 그 곳(?) 도 bcrypt 를 사용 하고 있습니다. 아마 아래 라이브러리 사용 하고 있을 겁니다. 다만 npm install 을 할 때 컴파일을 하는데, 파이썬이 필요 했던 걸로 기억이... 다른 라이브러리도 괜찮은 게 있다면 추천 바랍니다. ㅎㅎ

### 참고 
- bcrypt : [Naver D2 - 안전한 패스워드 저장](http://d2.naver.com/helloworld/318732)
- node bcrypt 라이브러리 : [kelektiv/node.bcrypt.js](https://github.com/kelektiv/node.bcrypt.js)

**Comment by ChangJoo-Park** [comment]
bcrypt가 비밀번호를 위해서 나온거라 선택의 여지가 딱히 없는걸로 알고있어요 ;ㅂ;

https://www.npmjs.com/search?q=keywords:bcrypt

**Comment by rkdgusrnrlrl** [comment]
@fobid [dcodeIO/bcrypt.js](https://github.com/dcodeIO/bcrypt.js) 쪽이 괜찮아 보기긴 합니다. 의존성 문제도 없고, 인기도 있는 편이여서, 다만 last commit 이 1년 전이라...어떤가요. 괜찮다면 제가 작업 해보겠습니다. (>3<)/

ps. 근데 Owner 아니면 이슈를 assign 못하나요??

**Comment by fobid** [comment]
@rkdgusrnrlrl organizations 운영을 해 본 적이 없어서 잘 모르겠는데, 설정 한 번 뒤져볼게요.

**Comment by fobid** [comment]
@rkdgusrnrlrl members 권한을 변경했는데, 한 번 assign 해보시고 안되면 다시 말씀해주세요.

**Comment by rkdgusrnrlrl** [comment]
@fobid  되었습니다. 감사합니다. (_ _)ㅎㅎ

**Comment by fobid** [comment]
@rkdgusrnrlrl 잘 부탁드립니다 🙏🏽

**Comment by rkdgusrnrlrl** [comment]
@fobid 한가지 도움 좀 부탁드립니다. ㅠㅠ 로컬에 mysql 띄워야 되는 것 같아서 띄웠습니다. 제가 실행한 방법은 `npm run dev` 로 실행했습니다.
근데 아래와 같은 에러가 뜹니다. 아마 제가 실행 방법을 잘 모르는 것 같습니다. ㅠㅠ 
```
Unable to connect to the database: { SequelizeAccessDeniedError: Access denied for user 'root'@'172.17.0.1' (using password: YES)
```

혹시 몰라 sequelizer 객체를 생성하기 전어 config 변수 값을 찍어보니 다음 과 같았습니다.(비밀번호는 공개하기 그래서 변수명을 넣었습니다.)

```
{ username: 'root',
  password: ${password},
  database: 'database_development',
  host: '127.0.0.1',
  dialect: 'mysql' }

```

왜 host 가 `127.0.0.1` 에서 `172.17.0.1`로 바뀐걸까요 ㅠㅠ

ps. 살려주세요 ㅠㅠ

**Comment by fobid** [comment]
@rkdgusrnrlrl config/config.json 파일에서 development 설정 맞추셨나요?

**Comment by fobid** [comment]
host가 바뀐건 잘 모르겠지만... development 설정 host를 `172.17.0.1`로 세팅하면 해결되지 않을까요?

**Comment by devjin0617** [comment]
다들 연휴때 일하시는건가요?

**Comment by rkdgusrnrlrl** [comment]
@fobid  아.....제가 myslq 비번일 잘못 알고 있어서... 이제 잘 동작 됩니다. ㅎㅎ
죄송합니다. 핫핫;;

**Comment by rkdgusrnrlrl** [comment]
@fobid 회원 가입 로직을 이해 안되서 질문 드립니다. 이메일로 회원 가입 하는 경우 파라미터를 어떻게 줘야 하는지 잘 모르겠습니다 ㅠㅠ 여러모로 번거롭게 해서 죄송합니다. ㅠㅠㅠ

`type` 필드 값이 enum 같이 정해진 값이 있을 것 같은데, 뭔지 모르겠어서 `email` 로 했습니다. 로직상 `userId` 가 없어야 email 쪽 가입 로직을 타는 것 같은데 ,`userId` 가 없으면 SNS 쪽 vailidate 쪽에서 걸려버립니다. ㅠㅠ

```
POST http://localhost:3000/api/signup

{
	"userId" : "rkdgusrnrlrl",
	"password" : "rkd123",
	"email" : "rkd@gmail.com",
	"type" : "email"
}
```

**Comment by fobid** [comment]
email 가입의 경우 email, password만 전달하면 됩니다.

회원가입 API 하나로 이메일 가입과 SNS 가입을 모두 처리하려니 이렇게 되어버렸네요.
그래서 email 가입과 SNS 가입 API를 분리하려고 생각하고있는데, 어떠신가요?

**Comment by fobid** [comment]
그보다 제가 주석을 우선 좀 달아놓도록 할게요.

**Comment by rkdgusrnrlrl** [comment]
@fobid  API 분리 하는 것이 괜찮은 것 같습니다. signup 쪽이 많이 가벼워질 것 같습니다. 👍

**Comment by fobid** [comment]
PR #31 에서 Email 로그인 & 회원가입과, SNS 연동 API를 분리했습니다.
