### ISSUE TITLE
API Response 형식

### ISSUE THREAD

**Issue by devjin0617** [travlog/travlog-server#39]
API 응답형식을 좀 더 개선해보려 합니다.

현재 res.send(API.RESULT... 이렇게 해놨었는데, 

그냥 소문자로 res.send(status.result(... 가 개발진행할때 더 괜찮지 않을까라고 생각됩니다.

에러상태도 아래와 같이 수정예정이니, 참고해주세용

```
module.exports = {
  result: () => {
    ...
  },
  code: {
    success: {
      code: 'SUCCESS',
      codeno: 2000
    },
    server_error: {
      code: 'SERVER_ERROR',
      codeno: 5000
    }
  }
}
```

더 좋은 방법 있으면 알려주세요 😢

**Comment by fobid** [comment]
전 다 좋아요 🤔

**Comment by rkdgusrnrlrl** [comment]
개인적으로는 parameter 검증(?) 을 위해서 errors 가 있으면 좋을 것 같습니다. 아래 형태 같으면 좋을 않을 까 싶습니다. 에러 문구는 어디를 참조 해야 할지 모르겠네요 ㅠㅠ
```
{
  errors : [
    { userId : "REQUIRE"},
    { userId : "STRING"}
  ]
}
```

**Comment by devjin0617** [comment]
@rkdgusrnrlrl 말씀해주신거 고민해봐야겠네용! 편하신대로 작업해주셔도 됩니당 ㅎㅅㅎ, 감사합니당 😄 

그리고 미들웨어에 추가하는 방법이 있었군요! 생각을 못하고 있었네요 😢

**Comment by devjin0617** [comment]
미들웨어에 추가하였습니다.
```
res.sendResult(API.CODE.SUCCESS, {
  hello: 'world'
})
```

**Comment by fobid** [comment]
고생하셨습니다 👍
