### ISSUE TITLE
Mongo 마이그레이션 작업

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [travlog/travlog-server#46]
Mongo 마이그레이션 이야기 하셨는데, 우선 라이브러리는 [mongoose](https://github.com/Automattic/mongoose) 쓰면 좋은 것 같습니다. 설정만 잡아 주면 그리 어렵지 않아고, mongoose 자체적으로 지원하는 함수 유용한 함수들이 더러 있습니다만... 제가 익숙한게 이거라서.....ㅠㅠ

사실 Mongo 쿼리가 익숙해서 다른 라이브러리 써도 크게 상관 없습니다. ㅎㅎ

기본적으로 아래 작업 정도가 필요 할 거 같습니다.
- [x] Mongo 클라이언트 라이브러리 선정
- [x] MySQL 스키마 Mongo 스키마로 변경한 모델 결정
- [x] MySQL 스키마 Mongo 스키마로 마이그레이션
- [x] 기존 함수 중 Mongo 스키마 변경 된 부분 마이그레이션

더 필요한 작업이 있을까요??

**Comment by fobid** [comment]
데이터가 정형화 되어있고, 변경이 적은 데이터(현재는 location, 추후 가계부 기능의 대분류, 소분류 등 서비스 관리 차원에서만 변경)는 RDBMS,
변경이 잦은 데이터는 NoSQL을 생각하고 있습니다.

**Comment by fobid** [comment]
따라서 현재는 location을 제외 한 모든 모델을 mongo로 migration 해도 되지 않을까 싶습니다.

**Comment by fobid** [comment]
@rkdgusrnrlrl 님을 맹신합니다.

**Comment by rkdgusrnrlrl** [comment]
맹...맹신 하시면 안됩니다. 제가 아직 경험이 적어서ㅠㅠ
PR 은 작업 코드를 보여주기 위해 올린거라, 다른 스키마들 마이그레이션 및  기존 관련 함수 수정 해야 할 것 같이 재오픈 합니다. 두작업 진행 후 한번에 PR 올리겠습니다.

**Comment by fobid** [comment]
@rkdgusrnrlrl 고생이 많습니다.

**Comment by fobid** [comment]
모든 schema에서 id를 Number가 아닌 UUID를 사용하려고 합니다.
이에 대해 어떻게 생각하시나요?

**Comment by rkdgusrnrlrl** [comment]
@fobid  Number 로 하면 자동 증가를 위해 테이블(collection)이 추가로 필요해 UUID 가 나을 것 같습니다.

**Comment by fobid** [comment]
mongo에서 UUID를 사용하는게 더 효과적이라고 한다면,
migration 하지 않은 데이터에 대해, RDB 에서도 UUID 를 사용하는 것은 어떤가요?

**Comment by rkdgusrnrlrl** [comment]
@fobid  괜찮을 것 같습니다. 우선 제가 생각하는 UUID 와 Number 의 장단점 은 아래와 같을 것 같습니다.
- UUID 를 사용 하면 로직에서 생성하기 때문에 로직상 Insert 전 ID 값 이 필요 한 경우 쉽게 해결이 가능합니다.
- Number(정확히 auto increase 기능 - 자동 번호 할당) 을 쓰면 API 서버에서 ID 를 생성해야 되서 서버쪽 작업이 필요합니다.
- ID 노출시 Number 부분이 깔끔 합니다. (개인적인 의견)

개인적으로 UUID 를 선호합니다. 서버쪽 작업이 크지 않고 UUID 생성에 대한 추가 비용(CPU 연산) 들겠지만, 아주 작을 것 같습니다. 하지만 로직상에서 간혹 생성전에 ID 값이 필요 한 경우가 있는데, mysql 에서 ID 값을 알려주기는 하지만 깔끔한 방식은 아닙니다.

**Comment by fobid** [comment]
UUID 당첨!
migration 작업은 잘 진행되고 있나요?
개인적인 의견이지만, API 테스트 없이 코드 작업만 후딱 끝내고, merge, 그리고 로컬에서 터트려도(?) 괜찮을 것 같습니다.
#43 작업을 해야되서, 저도 migration 된 db로 작업을 했으면 합니다.

**Comment by fobid** [comment]
너무 부담이었나요 ㅠㅠ 저도 그러면 안되지만, 맨날 개발 덜 된거 올려버리는데 ㅠㅠ

**Comment by rkdgusrnrlrl** [comment]
@fobid 너무 부담은 아닙니다. 개인적으로 성격이 걱정이 많아서, 그런거애요. ㅎㅎ 
스키마 작업이랑 커넥션 부분은 1일이면 대략 끝날 것 같고, 함수 부분은 대략적인 교체는 1일이면 되지 않을까 싶습니다. ㅎㅎ

**Comment by fobid** [comment]
@rkdgusrnrlrl 쉬엄쉬엄 하세요~
migration 과정에서 충돌나는 부분은 `refactring/change-schema-by-mongo` branch 에서 저도 작업하도록 할게요.

**Comment by ChangJoo-Park** [comment]
@rkdgusrnrlrl 질문이요

MongoDB 자체 API를 사용하는거랑 mongoose를 통해 사용하는거 두가지 장단점이 어떤게 있을까요 
예전부터 MongoDB를 쓰면 mongoose를 껴서 사용하는게 습관이 되서 별 생각을 안하고 있었는데 
왠지 현구님은 고민해보셨을거같아서..

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park  그렇게 크게 고민 하지않았습니다만 최근에 이 프로젝트를 하면서 고민 했는데, 내가 쓰는 기능은 mongodb-native 를 쓰는 거나 별 차이가 없더라구요. 제가 느낀 장단점 정리 해봅니다. ㅎㅎ

## mongoose 장점
- 스키마 정의
- 체인 형태의 쿼리
- 프로미스

## mongoose 단점
- 일부 기능이 불안정 (ex : 쿼리 타임아웃 Error)

개인적으로 쿼리는 왠만하면 MongoDB 쿼리를 쓰는 것을 지향합니다. 이유는 MongoDB Client 나 MongoShell(터미널......) 작업시 이질감을 덜기 위해 순수 쿼리를 사용 합니다. mongoose 는 ODM 이라고 부르는데, 이는 리턴 되는 값이 순수 json 이 아니라 mongoose 인스턴스인데(ORM 같이) 사실 이거의 필요성을 잘 못느끼겠습니다. ㅠㅠ

거의 MongoDB 자체 API 로 mongoose 를 쓰고 있어서 그런것 같습니다.  ㅠㅠ

**Comment by ChangJoo-Park** [comment]
아 그렇군요 ;ㅂ;
mongoose의 스키마 정의 하는거 부분(Model)이 되게 매력적이라고 생각해서 그냥 썼었어요
비추하는 분들이 많아서 질문드려봤어요 감사합니다 (__ )
