### ISSUE TITLE
기존 스키마 Mongo 스키마로 변경

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [travlog/travlog-server#47]
- 기존 스키마 Mongo 스키마로 변경
- destination, note, user, account 정도 Mongo 스키마로 변경

**Comment by rkdgusrnrlrl** [comment]
@fobid 스크마 마이그레이션 작업을 진행 중인데 질문이 있습니다. `User.profilePicture` 은 url 을 받는 것 같은데 full url(http://travlog.com/file/profile.png) 형태로 받나요 아님 파일명(profile.png) 만 받을 까요??

**Comment by fobid** [comment]
많이 작업하셨네요.
@rkdgusrnrlrl full url과 혹시 모를 상황을 대비하여 파일명을 따로 저장하면 어떨까요?

**Comment by fobid** [comment]
그리고 `User.profilePicture`, `Account.profilePicture` 두 가지가 있는데,

Account는 3rd party oauth 계정 정보를 모두 저장하게 됩니다.

oauth로 user를 처음 생성할 때,
`user.profilePicture = account.profilePicture` 데이터를 복사합니다.
(하지만 로직은 구현되지 않았습니다..)

그리고 이후에 사용자가 직접 사진을 변경하려고 하면, user.profilePicture를 변경합니다.
(역시 기능은 구현되지 않았습니다..)

**Comment by rkdgusrnrlrl** [comment]
#48 
아 그렇군요 둘다 보관할 필요가 있겠네요 ㅎㅎ 해당 작업을 하다 보니 mongoose 사용 방식(?) 이나 테스트 코드 등에 합의가 필요 할 것 같아 일부작업 부분만 테스트 코드로 만들어 PR 올렸습니다. 혹시 이견이나 설명이 더 필요한 부분 있으시면 적어주시면 좋을 것 같습니다.

**Comment by fobid** [comment]
@rkdgusrnrlrl 을 맹신합니다.
