### ISSUE TITLE
테이블명 불일치

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [travlog/travlog-server#49]
- `/api/signup` 호출이 아래와 같은 에러가 떻습니다.
```
SequelizeDatabaseError: Table 'database_development.accounts' doesn't exist
```
- 테이블은 확인 해보니 `Accounts` 로 되어 있었습니다.
- 우선 `Accounts`(첫글자 대문자), `accounts`(전부 소문자) 중 어느쪽이 맞는 지 궁금합니다. 
- 혹시 또 제가 뭔가 잘 못 한건가요 ㅠㅠ

**Comment by fobid** [comment]
초반 sequalize 작업 시 대문자로 시작을 했었습니다.
이후에 table join result를 json으로 만들 때, join 된 테이블 명이 대문자의 json key로 만들어지는 것을 확인하고, 모두 소문자로 바꾸는 작업을 했습니다.
그 과정에서 누락 된 것 같습니다 ㅠㅠ

**Comment by rkdgusrnrlrl** [comment]
@fobid 그러면 마이그레이션 코드를 소문자로 돌려 놓고 PR 올리면 될까요?? ㅎㅎ

**Comment by fobid** [comment]
대문자든 소문자든 뭐로만 통일되면 될 것 같습니다.
제가 db와 서버쪽 컨벤션? 네이밍 규칙을 몰라서.... 부탁드립니다. ㅋㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
db 쪽은 캐바케인데 처음에 배웠을 때는 대문자 snake (예 : USER, USER_BASKET) 으로 했었는데, 소문자 snake(예 : user, user_basket) 를 쓰기도 합니다. camel 형태(예 : userBasket) 은 좀 드문 것 같습니다. 

저희는 소문자로 진행하는 것이 좋을 것 같습니다. 마이그레이션 코드에서 변경만 하면 되서 작업이 많지 않고 첫글자만 대문자 쓰는 경우도 흔하지는 않습니다. ㅎㅎ 그럼 소문자로 진행 하겠습니다. ㅎㅎ
