### ISSUE TITLE
header에 authorization 에 토큰 값을 넣어줘야 하는데 어떻게 넣어줘야 하나요?

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [travlog/travlog-server#52]
- 저는 단순히 `token` 값을 넣어주면 될 줄 알아 아래와 같이 작성 했는데 에러가 났습니다.
```
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJ1X2UxZDQzZjQwLTY5ZTktMTFlOC1hNjJmLTg3ODZjODNlODhjMiIsInByb3ZpZGVyIjoidHJhdmxvZyIsImlhdCI6MTUyODQ1MTU5OX0.SZIXa4dqIRS80vy2uyxLQa7AEa_A4FGL7W72hq4zkGI
```
- `lib/auth.js` 에 jwt 인증 미들웨어에서 header 에서 가져온 토큰은 다음과 같이 spilit 하는 건가요??
```
 var authorization = req.headers["authorization"]

    if (authorization) {
        const bearerToken = authorization.split(' ')[1]

        try {
            const decodedToken = jwt.verify(bearerToken, TRAVLOG_SECRET)
            if (decodedToken && decodedToken.uid && decodedToken.provider) {

                req.token = bearerToken
                req.user = await User.getUserByUserIdAndProvider(decodedToken.uid, decodedToken.provider)

                if (req.user) {
                    return next()
                }
            }
        } catch (e) {
            console.error('ensureAuthorized: ', e)
        }
    }
    res.sendResult(API.CODE.ERROR.NOT_AUTHORIZED, {
        msg: 'call 911 carrera 4 gts cabriolet'
    })
```

ps. 혹시 테스트를 위해 POSTMAN 요청들 갖고 계시다면 export  부탁드려도 될까요??

**Comment by fobid** [comment]
master branch 를 제외 한 branch 에서 projectDir/API.http 파일을 열어보시면 postman 없이 api call해 볼 수 있습니다.

그래서 저는 postman을 사용하지 않습니다.

authorization은 ’Bearer {accessToken}’ 형태로 보내셔야 합니다.(공백 split 코드가 있는 이유)

API.http 파일에 보시면 AUTHORIZATION 을 변수로 하여 사용하고 있으니, accessToken 부분만 유효한 token으로 바꾸시면 바로 테스트 가능 할 거거에요.

**Comment by ChangJoo-Park** [comment]
@rkdgusrnrlrl  
VSCode를 쓰시면 
https://marketplace.visualstudio.com/items?itemName=humao.rest-client 이 익스텐션을 설치하세요

**Comment by rkdgusrnrlrl** [comment]
@fobid 덕분에 좋은거 알고 갑니다. rest 테스트 하는 툴이 내장 되어 있는데 그걸로 어떻게 해볼 수 있지 않을까 싶습니다. `API.http` 어떤 특정 문법이 있는 건가요??

**Comment by rkdgusrnrlrl** [comment]
....그냥 해당 파일 열면 실행 할 수 있더군요. ㄷㄷㄷ 참고를 위해 링크 첨부 합니다. 
- [IntelliJ의 .http를 사용해 Postman 대체하기](http://jojoldu.tistory.com/266)
