### ISSUE TITLE
질문입니다 🙃 

### ISSUE THREAD

**Issue by ChangJoo-Park** [travlog/travlog-server#54]
성태님 안녕하세요

성태님이 2019년 6월에 교토에 방문한다고 생각했을 때 가장 필요한게 뭔가요?

몇박이었죠? + 도시는 교토 하나인가요?

여행 얘기를 조금 남겨주세요 

---

저는 9박10일 독일여행이고 코스 짜는게 스트레스에요 
돈관리는 제가 안하니까 관심없구요

**Comment by ChangJoo-Park** [comment]
저는 프랑크푸르트 인 / 아웃이고

프랑크푸르트 - 하이델베르크 - 프랑크푸르트 - 함부르크 - 베를린 - 프랑크푸르트 

이 순서로 이동할거같거든요 그래서 각지역 안에서 무엇을 보고 먹고 쉬고 하는게 중요해요

**Comment by fobidlim** [comment]
교토 내에서만 있을거에요.
그래서 도시는 교토 하나 뿐이고, 가려는 장소는 많아요.
저는 먹고 쉬고 사진찍으러 가는건데요, 가려는 장소가 많다보니 각 장소에서 다른 곳으로 이동 경과 시간을 얼추 알고있어야되는게 중요해요.
대부분이 마감시간이 있기때문에 시간 계산을 잘 해야되요.
시간 계산 해보며 답 안나오면 장소의 순서를 바꾸기도 하구요.

**Comment by ChangJoo-Park** [comment]
_이동시간_ 이 중요한거네요

해당 장소의 상세적인것도 있겠네요

---

- 그럼 가계부는 중요하지않네요?
- 타임존도 별로 안중요한거같은데요?

**Comment by fobidlim** [comment]
맞아요. 저에겐 장소의 순서가 중요하구요,
가계부와 타임존은 *제가 생각하는* 핵심에 영향을 미치지 않으며, 추후 부가적인 정보를 채우기 위함입니다.

**Comment by ChangJoo-Park** [comment]
그럼 여행가서 USIM 쓰나요 안쓰나요

오프라인지도는 혹시 쓰시나요?

**Comment by ChangJoo-Park** [comment]
저의 일정 정하는 방법

- 꼭 가고싶은 곳을 고른다
- 그 주변을 본다
- 간다

순위가 낮으면 안감

**Comment by boraJeon** [comment]
나라에 따라 다르지 않을까요? 유럽은 유심이 잘되어있어서 유심사서 쓰기 편한데 일본이나 동남아쪽은 어떤지 모르겠네요 그쪽은 보통 에그 사서 들고다니거나 로밍하는거같아요 그리고 저는 항상 가능하면 오프라인지도를 다운받아 갑니다.

**Comment by ChangJoo-Park** [comment]
일본은 와이파이 도시락 쓰잖아요

**Comment by boraJeon** [comment]
ㅇㅎ 저게 에그랑 또 다른가요?ㅋㅋㅋ

**Comment by ChangJoo-Park** [comment]
에그에요 ㅋㅋㅋ

**Comment by fobidlim** [comment]
주로 정보를 찾기 위한 용도는 아닌데, 응급상황을 대비해서 유심을 사요.
지도를 자주 보는 편은 아니지만, 유심이 있다보니 오프라인 지도는 따로 사용하지 않구요.
급한 상황에서 어떻게 될지 모르니까 유심이 있더라도 가급적이면 해외에서 데이터를 쓰고싶지는 않아요.

일본에 갈 때 유심과 에그를 고민하다가, 둘이 여행가서 서로 떨어져있는 상황이 생길까봐 유심으로 선택했어요.
외국에서 한 번은 서로 잃어버린 적이 있었거든요.

**Comment by fobidlim** [comment]
트래블로그 _기획 의도_ 와 _기대 효과_ 를 정리해봤습니다.

https://github.com/travlog/travlog-idea/issues/2#issuecomment-494759971

**Comment by ChangJoo-Park** [comment]
아 러시아 이야기가 생각이났어요 이럴수가

**Comment by ChangJoo-Park** [comment]
> 기억을 더듬어봤습니다
> 
> **기획 의도**
> 
> 1. 여행 일정동안 가고싶은 장소가 많은데, 이동시간을 고려하는 일정을 만들기 위해 구글맵으로 장소 to 장소로 소요 시간을 계산하고, 모든 일정을 확인하기 위해 메모장에 따로 정리하는 것이 매우 불편.
> 
> **기대효과**
> 
> 1. 효과적인 여행 경로를 사전에 준비하면 해외 여행지에서 구글링하지 않아도 됩니다.
> 2. 과거 여행 기록을 참고하며 새로운 여행 예산을 준비할 수 있습니다.
> 3. 같은 도시를 여행하려는 사람들에게 나의 기록을 토대로 추천을 할 수 있습니다.


이동시간 고려
---

각 지역간 이동거리는 실시간으로 파악할 수 있어야하는가
- 각 공간별 위치는 보통 여행 전에 대부분 파악하지 않을까요?
- 여행 경로는 단순히 여기 다음은 여기를 간다 정도면 되지않을까요?


기대 효과 이전에 의도에서 필요한거만 뽑아보죠 
타임어택입니다 기간은 2주도 안남은거죠?


+

@boraJeon 님 예전에 여행 계획하신거 한번 공유부탁드려요 (가능하시면)

**Comment by ChangJoo-Park** [comment]
아 그리고..

그냥 궁금한건데 한국이든 외국이든, 같은 곳을 여러번 여행해보신 경험이 있으신가요?

**Comment by boraJeon** [comment]
전 같은곳 여러번 해본 경험이 없습니다 ㅠ_ㅠ (안가본데 가보기도 벅차서)

**Comment by boraJeon** [comment]
저의 영국(런던) 여행 계획서입니다. 참고로 못갔습니다 😭 https://www.evernote.com/l/AaZghM4WyL5F570BZpdBwmjYYgSQnM3-WJU

**Comment by fobidlim** [comment]
네 기대효과는 먼 미래를 바라본거니까요, 기획의도에서 최소한으로 시작하는 것이 좋겠습니다.

- 각 공간별 위치는 보통 여행 전에 대부분 파악하지 않을까요?
> 해외 기준으로 말씀드리자면, 대략적인 위치는 세계 지도 기준으로 파악할 수 있구요, 낯선 장소, 낯선 지명, 낯선 언어와 가게 이름 등 메모를 다시 확인하지 않으면 제대로 암기하기가 쉽지 않습니다. (갈 곳이 많다면 더욱 힘들어요)

- 여행 경로는 단순히 여기 다음은 여기를 간다 정도면 되지않을까요?
> 이 문제의 최소 스펙은 여기 다음은 어디일지 순서를 파악할 수 있으면 될 것 같아요.

**Comment by fobidlim** [comment]
외국과 한국 모두 같은 도시를 3번 이상 여행해 본 경험이 있습니다.
블라디보스톡에서 다시 가보고 싶은 곳은 두 곳 있습니다.

**Comment by lus-ik** [comment]
저는 주로 여행할 때 해당 지역의 가고 싶은 음식점, 관광지, 숙소 등을 다 구글 맵에 등록하는 것부터 시작해요.
네이버나 인스타에서 찾고 그 위치를 구글 맵에 일단 다 등록해놔요!
그 다음에 구글 맵을 보면서 어떤 루트로 갈지 루트짜는 편입니다
이때 걸러낼 곳 걸내고, 최대한 이동하기 쉬운 루트로 짜는 것같아요!

**Comment by ChangJoo-Park** [comment]
> 저는 주로 여행할 때 해당 지역의 가고 싶은 음식점, 관광지, 숙소 등을 다 구글 맵에 등록하는 것부터 시작해요.
> 네이버나 인스타에서 찾고 그 위치를 구글 맵에 일단 다 등록해놔요!
> 그 다음에 구글 맵을 보면서 어떤 루트로 갈지 루트짜는 편입니다
> 이때 걸러낼 곳 걸내고, 최대한 이동하기 쉬운 루트로 짜는 것같아요!

오 저랑 비슷하네요 ㅋㅋ 마이맵 써보셨나요?

**Comment by ChangJoo-Park** [comment]
일단 웹사이트 / 안드로이드가 개발중이니 닫아도 될거같아요
직접 써보는 수밖에 (_ _ )
